# Generated by Django 5.0.7 on 2025-09-30 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_search_index'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='post_content_gin',
        ),
    ]
